version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The first step
          command: gradle test
      - store_test_results:
          path: build/test-results
      - run:
          name: Jar step
          command: gradle jar
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
