version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Testing step
          command: |
            pwd
            ls
            gradle test
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Packaging step
          command: | 
            pwd
            ls
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: build
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
workflows:
  version: 2
  test-and-package:
    jobs:
      - test
      - package:
          requires:
            - test
